//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECT_DEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int IdTin { get; set; }
        public int IDLoai { get; set; }
        public string TieuDeTin { get; set; }
        public string NoiDungTin { get; set; }
    
        public virtual TheLoaiTin TheLoaiTin { get; set; }
    }
}
